import request from '@/utils/request'

export const getDashboardApi = () => request.get('/admin/dashboard')
export const getUsersApi = (params) => request.get('/admin/users', { params })
export const updateUserStatusApi = (id, deleted) => request.put(`/admin/users/${id}/status`, null, { params: { deleted } })
export const updateUserRoleApi = (id, roleCode) => request.put(`/admin/users/${id}/role`, null, { params: { roleCode } })
export const getAdminProductsApi = (params) => request.get('/admin/products', { params })
export const createProductApi = (data) => request.post('/admin/products', data)
export const updateProductApi = (id, data) => request.put(`/admin/products/${id}`, data)
export const updateProductStatusApi = (id, status) => request.put(`/admin/products/${id}/status`, null, { params: { status } })
export const getCategoriesApi = () => request.get('/admin/categories')
export const createCategoryApi = (data) => request.post('/admin/categories', data)
export const updateCategoryApi = (id, data) => request.put(`/admin/categories/${id}`, data)
export const deleteCategoryApi = (id) => request.delete(`/admin/categories/${id}`)
export const getOrdersApi = (params) => request.get('/admin/orders', { params })
export const updateOrderStatusApi = (id, status) => request.put(`/admin/orders/${id}/status`, null, { params: { status } })
export const getMakeupServicesApi = (params) => request.get('/admin/makeup-services', { params })
export const updateMakeupServiceStatusApi = (id, status) => request.put(`/admin/makeup-services/${id}/status`, null, { params: { status } })
export const getArtistApplicationsApi = (params) => request.get('/admin/applications/artist', { params })
export const reviewArtistApplicationApi = (id, action) => request.put(`/admin/applications/artist/${id}`, null, { params: { action } })
export const getMerchantApplicationsApi = (params) => request.get('/admin/applications/merchant', { params })
export const reviewMerchantApplicationApi = (id, action) => request.put(`/admin/applications/merchant/${id}`, null, { params: { action } })
